name: Deploy

on:
  #  push:
  #    branches:
  #      - main # Adjust to your deployment branch
  workflow_dispatch: # Enable manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest


    steps:

      - name: Debug
        run: |
          echo "Checking SSH configuration..."
          echo "Hostname: ${{ secrets.SERVER_HOST }}"
          echo "SSH Username: ${{ secrets.SERVER_USERNAME }}"
          echo "SSH Username Len: ${{ secrets.SERVER_USERNAME }}" | wc -c
        env:
          SSH_HOST: ${{ secrets.SERVER_HOST }}
          SSH_USER: ${{ secrets.SERVER_USERNAME }}