name: Deploy

on:
  #  push:
  #    branches:
  #      - main # Adjust to your deployment branch
  workflow_dispatch: # Enable manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest


    steps:

      - name: Debug
        run: |
          echo "Checking SSH configuration..."
          echo "Hostname: ${{ secrets.SERVER_HOST }}"
          echo "SSH Username: ${{ secrets.SERVER_USERNAME }}"
#          echo "SSH Key: ${{ secrets.SSH_KEY }}" | wc -c
        env:
          SSH_HOST: ${{ secrets.SERVER_HOST }}
          SSH_USER: ${{ secrets.SERVER_USERNAME }}

      # Step 5: SSH into the server and deploy
      - name: Deploy on Server
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/erp-web:latest
            docker stop erp-web || true
            docker rm erp-web || true
            docker run -d --name erp-web -p 80:80 ${{ secrets.DOCKER_USERNAME }}/erp-web:latest